### ISSUE TITLE
relax bound on transformers to allow 0.5.*

### ISSUE THREAD

**Issue by cartazio** [ekmett/reducers#22]
seems to build fine with my 8.0rc4 ghc 
would you like me to just relax the bound on https://hackage.haskell.org/package/reducers-3.12.1
or would cutting a new release make sense?

**Comment by laura-dietz** [comment]
I believe this should be resolved.

**Comment by RyanGlScott** [comment]
Indeed, this was fixed in fda2fbaed78b43c9fd218eb41e9e50cd1ac8cc0a.
